import {Camera, Upload, Trash2, LoaderCircle} from 'lucide-react';
import React,{useState,useRef} from 'react';
import {useAuth} from '../../context/AuthContext';
export function ProfilePhoto(){
  const inputRef=useRef(null);
  const {user,updateAvatar}=useAuth();const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function upload(file){if(!file)return;setError('');setBusy(true);let url;
    try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024)throw new Error('Choose a JPG, PNG or WebP photo up to 8 MB.');
      url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();
      const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const ctx=canvas.getContext('2d');
      const side=Math.min(img.width,img.height);ctx.drawImage(img,(img.width-side)/2,(img.height-side)/2,side,side,0,0,256,256);
      let image=canvas.toDataURL('image/png').split(',')[1];
      if(image.length>230000){const smaller=document.createElement('canvas');smaller.width=192;smaller.height=192;smaller.getContext('2d').drawImage(canvas,0,0,192,192);image=smaller.toDataURL('image/png').split(',')[1];}
      await updateAvatar(image);
    }catch(e){setError(e.message||'Could not read that photo.');}finally{if(url)URL.revokeObjectURL(url);setBusy(false);}}
  async function remove(){setBusy(true);setError('');try{await updateAvatar(null);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section aria-label="Profile photo" className="rounded-2xl border border-primary/15 bg-primary-light/40 p-5 sm:p-6"><div className="flex flex-col sm:flex-row items-start sm:items-center gap-5"><div className="relative shrink-0"><div className="w-24 h-24 rounded-full bg-white border-4 border-white ring-1 ring-primary/15 text-primary overflow-hidden flex items-center justify-center text-3xl font-bold shadow-sm">{user.avatarUrl?<img src={user.avatarUrl} alt="Your profile" className="w-full h-full object-cover"/>:user.name?.charAt(0)}</div><span className="absolute bottom-0 right-0 w-8 h-8 rounded-full bg-primary text-white border-2 border-white flex items-center justify-center"><Camera size={14}/></span></div><div className="min-w-0"><h4 className="font-bold text-base">Make it your profile</h4><p className="text-xs text-text-secondary mt-1">Add a photo so your account feels a little more like you.</p><div className="flex flex-wrap items-center gap-3 mt-4"><input ref={inputRef} id="profile-photo" aria-label="Choose profile photo" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}} className="hidden"/><button type="button" disabled={busy} onClick={()=>inputRef.current?.click()} className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-primary text-white text-sm font-bold shadow-sm hover:bg-primary-dark focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary disabled:opacity-60">{busy?<LoaderCircle size={16} className="animate-spin"/>:<Upload size={16}/>} {busy?'Saving…':user.avatarUrl?'Change photo':'Add photo'}</button>{user.avatarUrl&&<button type="button" disabled={busy} onClick={remove} className="inline-flex items-center gap-1.5 text-sm font-semibold px-3 py-2.5 rounded-xl border border-border bg-white text-text-secondary hover:text-red-700 disabled:opacity-50"><Trash2 size={14}/>Remove</button>}</div><p className="text-[11px] text-text-muted mt-3">JPG, PNG or WebP · Up to 8 MB · Automatically cropped to a square</p></div></div>{busy&&<p role="status" className="sr-only">Saving photo…</p>}{error&&<p role="alert" className="text-red-700 text-sm mt-3">{error}</p>}</section>;
}
