import React from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, FileText, ArrowLeft } from 'lucide-react';
import { useCatalog } from '../context/CatalogContext';
import { useLanguage } from '../context/LanguageContext';

function Contact() {
  const { settings } = useCatalog();
  return <address className="not-italic rounded-2xl bg-primary-light p-5 space-y-2"><strong className="block text-text-primary">{settings.storeName || 'Al Kabeer H Mart'}</strong><p>{settings.address}</p>{settings.email && <a className="block text-primary-dark underline break-all" href={'mailto:'+settings.email}>{settings.email}</a>}{settings.phone && <a className="block text-primary-dark underline" href={'tel:'+settings.phone}>{settings.phone}</a>}<p className="text-sm">For order support, include your order number. For a privacy request, use the email or phone associated with your account so we can verify the request.</p></address>;
}
function Section({id,title,children}) {return <section id={id} className="scroll-mt-28"><h2 className="text-lg font-black text-text-primary mb-3">{title}</h2><div className="space-y-3 text-sm sm:text-base text-text-secondary leading-relaxed">{children}</div></section>;}
function LegalLayout({type,children}) {
  const { t } = useLanguage();
  const privacy=type==='privacy', Icon=privacy?ShieldCheck:FileText;
  return <article className="max-w-4xl mx-auto px-4 sm:px-6 py-8 sm:py-12"><Link to="/" className="inline-flex items-center gap-2 text-primary font-semibold text-sm"><ArrowLeft size={16}/>{t('productDetail.backToStore')}</Link><header className="py-8 border-b border-border mb-8"><span className="inline-flex p-3 rounded-2xl bg-primary-light text-primary mb-4"><Icon size={28}/></span><h1 className="text-3xl sm:text-4xl font-black text-text-primary">{privacy ? t('footer.privacyPolicy') : t('footer.termsOfService')}</h1><p className="mt-3 text-text-secondary">{privacy?'How we use information when you shop with us.':'What to expect when you place an order with our store.'}</p><p className="text-xs text-text-muted mt-4">Last updated: 22 September 2026</p></header><div className="space-y-9">{children}</div><nav aria-label="Related policies" className="mt-10 pt-6 border-t border-border"><Link className="text-primary font-bold underline" to={privacy?'/terms-of-service':'/privacy-policy'}>{privacy ? t('footer.termsOfService') : t('footer.privacyPolicy')}</Link></nav></article>;
}
export function PrivacyPolicy() {
  return <LegalLayout type="privacy">
    <Section id="information" title="1. Information used by the store"><p>We use the information you provide to create an account and fulfil orders: your name, email address or phone number, saved delivery addresses, items ordered, prices, payment preference and order history. If you add a profile photo, it is stored with your account and shown to you while signed in. Reviews publish your display name, rating and feedback on the product page; you can edit or remove your own feedback. Your password is stored as a one-way hash, rather than as readable text. Payment records can include a payment-provider reference and verification status.</p></Section>
    <Section id="purpose" title="2. Why we use this information"><p>We use account and order information to sign you in, prepare and deliver purchases, confirm availability, answer support requests, process cancellations or refunds, and protect accounts and store operations against misuse. Order information is available to authorised store administrators.</p></Section>
    <Section id="sharing" title="3. WhatsApp, payments and delivery"><p>When you place an order, the site opens WhatsApp with your selected items, total, name, phone number, delivery address and payment status in a prefilled message. Opening the WhatsApp link shares that content with WhatsApp; you must tap Send inside WhatsApp to send it to the store. WhatsApp processes information under its own privacy policy.</p><p>If you use online checkout, Razorpay receives the information needed to process the payment, such as your name, phone number and order amount. Card details, PINs and OTPs are handled by the payment service, not stored in this store’s order database. Do not send card numbers, CVVs, UPI PINs or OTPs in a WhatsApp message.</p><p>Information necessary for delivery may be shared with the person delivering your order. Hosting and technical service providers may process information necessary to operate the site. Third-party product images and external links can also expose your network address to their providers.</p></Section>
    <Section id="storage" title="4. Cookies and browser storage"><p>We use a session cookie to keep you signed in. Choosing “Remember me” keeps a sign-in session for up to seven days; other sessions are limited to one day and the browser session. Your cart and language preference are stored in your browser. Clearing browser data removes these local preferences but does not delete orders already saved with the store.</p></Section>
    <Section id="retention" title="5. Stored records and security"><p>Account details, addresses and orders are stored in the store’s database. Records may be retained for order support, disputes, refunds and applicable record-keeping requirements. The site does not automatically delete your account or order history when you sign out. Contact us to request deletion or to ask about the records we hold.</p><p>We use password hashing, sign-in controls and administrator permissions to restrict access. Please protect your password and sign out on shared devices.</p></Section>
    <Section id="choices" title="6. Your choices and requests"><p>You can update your profile and saved addresses in My Account. Contact us to request access to, correction of, or deletion of your personal information, to withdraw consent where applicable, or to raise a privacy concern. We may need to verify your identity and may retain information needed for an outstanding order, a dispute or a legal requirement. We will explain any restriction that affects your request.</p></Section>
    <Section id="contact" title="7. Contact and policy changes"><p>Use the contact details below for privacy questions or complaints. Changes to how this service works may require updates to this policy; the latest version and update date will appear on this page.</p><Contact/></Section>
  </LegalLayout>;
}
export function TermsOfService() {
  return <LegalLayout type="terms">
    <Section id="store" title="1. Using the store"><p>These terms cover purchases and use of the Al Kabeer H Mart website. Provide accurate contact and delivery information, keep your account credentials private, and use the site only for lawful purchases. Do not attempt to access another person’s account, interfere with the service or submit fraudulent orders.</p></Section>
    <Section id="orders" title="2. Ordering and WhatsApp confirmation"><p>Checkout saves your order and opens WhatsApp with an order summary. Tap Send in WhatsApp to share the message with the store. The “Order Placed Successfully!” screen confirms that your order was saved; it does not prove a WhatsApp message was sent or that delivery has been confirmed.</p><p>The store confirms availability and delivery arrangements. If an item is unavailable or an order cannot be fulfilled, contact the store to agree on a change or cancellation. Any agreed substitution or change in price should be confirmed before delivery.</p></Section>
    <Section id="prices" title="3. Prices and payment"><p>Prices and checkout totals are shown in Indian rupees. Review the items, quantities, discount and delivery fee before placing an order. The saved order total is calculated by the store’s server. If a price changes before you submit, checkout asks you to review the new total.</p><p>Cash on delivery is payable when your order arrives. UPI and card payments use secure online checkout when enabled. The website verifies payment before opening WhatsApp. Unpaid online orders reserve stock for 30 minutes and are then cancelled. Selecting a method or sending an order on WhatsApp does not mean you have paid. Where online checkout is available, payment is confirmed only after verification by the payment provider. Never share a card number, CVV, OTP or UPI PIN with the store over chat.</p></Section>
    <Section id="delivery" title="4. Delivery"><p>Delivery is available to the service pincodes accepted at checkout. Delivery times shown on the site are estimates and can vary with stock, order volume, traffic and weather. Confirm the delivery time with the store. You are responsible for providing an accessible address and a reachable phone number.</p></Section>
    <Section id="cancellation" title="5. Cancellations, problems and refunds"><p>You can request cancellation from My Orders while an order is Processing. If it has been dispatched, contact the store for help. Please report a wrong, missing, damaged, spoiled or otherwise defective item promptly, with your order number and relevant details, so the store can investigate and arrange an appropriate remedy.</p><p>Cancellation of a paid order does not itself transfer money back to your account. The store must arrange the refund and confirm its progress; bank or payment-provider processing times may apply. A “Refund required” status means the refund still needs attention. Nothing in these terms limits rights or remedies available to you under applicable consumer law.</p></Section>
    <Section id="availability" title="6. Account and service availability"><p>Access to the site can be interrupted by maintenance, network problems or technical failures. If checkout gives an uncertain result, check My Orders before submitting another purchase. Contact the store with the order number if a payment was deducted but its status is unclear.</p></Section>
    <Section id="support" title="7. Support, complaints and changes"><p>For order questions, cancellations, refund assistance or complaints, use the contact details below and include your order number. Updates to these terms will be posted on this page. Keep a copy of your order confirmation for your records.</p><Contact/></Section>
  </LegalLayout>;
}
